### ISSUE TITLE
./configure no such file

### ISSUE THREAD

**Issue by pacocc** [ecashin/integrit#2]
Instructions say to run ./configure yet there is no such file.

**Comment by ecashin** [comment]
Hi.  There's an integrit project now.  The README implies that the tarballs are the releases, and they contain a `configure` script.

Does the advice in the README (second paragraph) help?  I bet this is the information you need and so am closing the issue.  Feel free to re-open in the integrit-project at github.com/integrit if you think there's more to it.

https://github.com/integrit/integrit/blob/master/README#L10
